const MOCK_SUMMARY_TEMPLATE = `<p class="mb-4">This risk assessment provides a comprehensive overview for '{projectName}', a large-scale {projectType} scheduled for {eventDate}. {attendeesInfo}The fundamental objective of this event is to ensure the absolute safety and security of all attendees, staff, and performers, while simultaneously delivering a memorable, high-quality entertainment experience. The key operational considerations for an event of this scale are multifaceted and require meticulous planning. They include the implementation of a robust crowd management strategy to prevent surges and ensure smooth flow, a multi-layered security plan to address potential threats, and detailed contingency plans to effectively manage potential disruptions such as adverse weather, technical failures, or medical emergencies.</p><p>Reflecting on the historical context of large-scale music festivals, it is evident that proactive and thorough management of ancillary services is a critical determinant of success. This includes the strategic placement and staffing of medical facilities to handle a range of incidents, maintaining impeccable sanitation standards across the venue, and coordinating with local authorities to manage transport logistics for a smooth ingress and egress of tens of thousands of people. Establishing this robust operational framework is instrumental not only in mitigating the common pitfalls associated with large events but also in building public trust and ensuring the project achieves its intended artistic and commercial success.</p>`;
const MOCK_RISKS = [
    { id: 1, risk: "Severe overcrowding in specific areas (e.g., front of stage, entry/exit points) leading to potential crushing and injury.", category: "Crowd Safety", impact: 5, likelihood: 3, mitigation: "Implement a phased entry/exit system, utilize crowd barrier systems to create separate zones, deploy experienced crowd spotters, and have clear emergency evacuation routes." },
    { id: 2, risk: "Adverse weather conditions (e.g., extreme heat, heavy rain, high winds) impacting attendee safety and event infrastructure.", category: "Environmental", impact: 4, likelihood: 4, mitigation: "Monitor weather forecasts continuously, provide free water stations and shaded areas, have a clear event cancellation policy, and ensure stage/tents are rated for high winds." },
    { id: 3, risk: "Major security incident, such as a targeted attack or large-scale public disorder, threatening attendee safety.", category: "Security", impact: 5, likelihood: 2, mitigation: "Implement comprehensive bag searches and screening at all entry points, maintain a highly visible security and police presence, utilize CCTV monitoring, and have a pre-agreed response plan with emergency services." },
    { id: 4, risk: "Theft of attendee property or unauthorized access to restricted areas (e.g., backstage) due to insufficient access control.", category: "Security", impact: 3, likelihood: 4, mitigation: "Deploy dedicated security personnel to monitor restricted access points, use RFID wristbands for zoned access, and provide clear messaging to attendees about keeping valuables secure." },
    { id: 5, risk: "Mass medical emergencies (e.g., heatstroke, dehydration, drug-related incidents) overwhelming on-site medical facilities.", category: "Medical", impact: 4, likelihood: 3, mitigation: "Provide multiple, clearly-signed medical tents staffed by qualified professionals, deploy roaming first aid teams, run a public health campaign about staying hydrated, and have clear escalation paths to local hospitals." },
    { id: 6, risk: "Critical technical failure, such as a complete power or main stage sound system outage, leading to show cancellation and potential crowd unrest.", category: "Operational", impact: 3, likelihood: 2, mitigation: "Have redundant power supplies (generators) for all critical systems, conduct thorough pre-show sound and equipment checks, and have technical support staff on standby for immediate response." },
    { id: 7, risk: "Insufficient sanitation facilities or water points, leading to public health issues and guest dissatisfaction.", category: "Logistics", impact: 2, likelihood: 4, mitigation: "Provide toilets and water access well above the minimum recommended ratio for the capacity, schedule frequent cleaning and restocking, and ensure clear signage to all facilities." },
];